name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    env:
      SNAKE_LENGTH: 1
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Juan11211
          svg_out_path: dist/github-contribution-grid-snake.svg
          length: ${{ env.SNAKE_LENGTH }}

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Increment snake length
      - name: Set snake length
        run: echo "SNAKE_LENGTH=$((SNAKE_LENGTH+1))" >> $GITHUB_ENV
